name       : skrooge
version    : 2.10.5
release    : 12
source     :
    - https://cdn.download.kde.org/stable/skrooge/skrooge-2.10.5.tar.xz : 56a0124dec34e6e96a5e71ff0e825a7ec79f32a69ef0ccdc5f0f9b753d8c3eb0
license    : GPL-2.0
component  : office.finance
summary    : Personal finance tool for KDE
description: |
    Skrooge is the personal finance management tool for KDE, with the aim of being highly intuitive, while providing powerful functions such as reporting (including graphics), persistent Undo/Redo, encryption, and much more.
patterns   :
    - doc : /usr/share/doc
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libKActivities)
    - pkgconfig(libofx)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(sqlcipher)
    - pkgconfig(sqlite3)
    - extra-cmake-modules
    - grantlee-devel
    - karchive-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kdesignerplugin-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kparts-devel
    - krunner-devel
    - kwallet-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - shared-mime-info
rundeps    :
    - qt5-quickcontrols
setup      : |
    %cmake -DSKG_BUILD_TEST=FALSE .
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 skrooge/icons_hicolor/256-apps-skrooge.png $installdir/usr/share/pixmaps/skrooge.png
    cd $installdir; qml_cache
