name       : skrooge
version    : 2.8.0
release    : 3
source     :
    - https://download.kde.org/stable/skrooge/skrooge-2.8.0.tar.xz : d96cd93666ef0ffe74860cff15df78a79f02e2e26b53fcfd1ff90ac5393de912
license    : GPL-2.0
component  : office
summary    : Personal finance tool for KDE
description: |
    Skrooge is the personal finance management tool for KDE, with the aim of being highly intuitive, while providing powerful functions such as reporting (including graphics), persistent Undo/Redo, encryption, and much more.
patterns   :
    - doc : /usr/share/doc
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libKActivities)
    - pkgconfig(libofx)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(sqlcipher)
    - pkgconfig(sqlite3)
    - extra-cmake-modules
    - grantlee-devel
    - karchive-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdelibs4support-devel
    - kdesignerplugin-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - knewstuff-devel
    - knotifyconfig-devel
    - kparts-devel
    - kwallet-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - shared-mime-info
rundeps    :
    - breeze-icons
setup      : |
    %patch -p1 < $pkgfiles/0001-Force-breeze-as-the-default-icon-theme.patch
    %cmake -DSKG_BUILD_TEST=FALSE .
build      : |
    %make
install    : |
    %make_install
