name       : skrooge
version    : 2.9.0
release    : 7
source     :
    - https://cdn.download.kde.org/stable/skrooge/skrooge-2.9.0.tar.xz : ad02403026b649203f0381cc599a7754d36f41cc75cc03d14e63bfdb666e7bb5
license    : GPL-2.0
component  : office.finance
summary    : Personal finance tool for KDE
description: |
    Skrooge is the personal finance management tool for KDE, with the aim of being highly intuitive, while providing powerful functions such as reporting (including graphics), persistent Undo/Redo, encryption, and much more.
patterns   :
    - doc : /usr/share/doc
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libKActivities)
    - pkgconfig(libofx)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(sqlcipher)
    - pkgconfig(sqlite3)
    - extra-cmake-modules
    - grantlee-devel
    - karchive-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kdesignerplugin-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kparts-devel
    - kwallet-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - shared-mime-info
rundeps    :
    - breeze-icons
setup      : |
    %patch -p1 < $pkgfiles/0001-Force-breeze-as-the-default-icon-theme.patch
    %cmake -DSKG_BUILD_TEST=FALSE .
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 skrooge/icons_hicolor/256-apps-skrooge.png $installdir/usr/share/pixmaps/skrooge.png
