name       : skrooge
version    : 2.16.2
release    : 22
source     :
    - https://cdn.download.kde.org/stable/skrooge/skrooge-2.16.2.tar.xz : 124e0928595be6c1ae0a879f4f1cd4631e7aced8c5273ccb92e128a4f2c2bb45
license    : GPL-2.0-or-later
component  : office.finance
summary    : Personal finance tool for KDE
description: |
    Skrooge is the personal finance management tool for KDE, with the aim of being highly intuitive, while providing powerful functions such as reporting (including graphics), persistent Undo/Redo, encryption, and much more.
patterns   :
    - doc : /usr/share/doc
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libKActivities)
    - pkgconfig(libofx)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(sqlcipher)
    - pkgconfig(sqlite3)
    - extra-cmake-modules
    - grantlee-devel
    - karchive-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kdesignerplugin-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kjobwidgets-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kparts-devel
    - krunner-devel
    - kwallet-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - shared-mime-info
rundeps    :
    - qt5-quickcontrols
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 skrooge/icons_hicolor/256-apps-skrooge.png $installdir/usr/share/pixmaps/skrooge.png
    %qml_cache || :
